site_name: Bienvenido a Apsys
site_url: https://mikelanuza03.github.io/ApsysDocumentation/

theme:
  name: material
  logo: logo_Apsys_white-ver.ico
  features:
    - toc.follow
  favicon: LOGO_APSYS.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      title: Tabla de contenidos
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav: 
  - Por donde empezar: 'index.html'
  - Usemos Visual Code: 'Usemos Visual Studio Code 6523405cead146ed9167afb69b843478/index.html'
  - Usemos Visual Studio: 'Usemos Visual Studio ee10e243d40246b480dced765d9016fb/index.html'
  - Usemos el gestionador de bases de datos: 'Usemos el gestionador de bases de datos fd9ae6110c8343dea703aaca3985a015/index.html'